# Generated by Django 5.0.6 on 2024-06-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_producto_creado_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='puntaje',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
