# Generated by Django 5.0.6 on 2024-06-28 09:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_rename_carrito_carro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='precio',
        ),
        migrations.AddField(
            model_name='carro',
            name='fecha_compra',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carro',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.producto'),
        ),
    ]
